# Generated by Django 4.1 on 2022-09-14 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="last_updated",
        ),
    ]
